#!/bin/bash
IP=$(ifconfig | grep --color=no -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep --color=no -Eo '([0-9]*\.){3}[0-9]*' | grep --color=no -v '127.0.0.1')
RED='\033[0;31m'
NC='\033[0m' # No Color

rebar3 compile

case "$1" in
    "")
	INDEX="1"
        ;;
    *)
	INDEX=$1
	;;
esac
if [ $? -eq 0 ]; then
    mkdir -p data
    rm -rf data/test.db
    erl -name "veronica${INDEX}@${IP}" -setcookie veronica -pa _build/default/lib/*/ebin/ -eval 'application:ensure_all_started(veronica).'
else
    printf "${RED}====> Compile error${NC}"
fi
