#!/bin/bash
IP=$(ifconfig | grep --color=no -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep --color=no -Eo '([0-9]*\.){3}[0-9]*' | grep --color=no -v '127.0.0.1')
RED='\033[0;31m'
NC='\033[0m' # No Color

RANDOM_STRING=$(date | md5 | head -c 10)
rebar3 compile

NODE_NAME="veronica_${RANDOM_STRING}@${IP}"
CMD_PING="net_adm:ping('${NODE_NAME}')"

if [ $? -eq 0 ]; then
    mkdir -p data
    rm -rf data/main
    erl -name ${NODE_NAME} -setcookie veronica -pa _build/default/lib/*/ebin/ -eval "${CMD_PING}" -eval 'application:ensure_all_started(veronica).'
else
    printf "${RED}====> Compile error${NC}"
fi
