#!/bin/bash
IP=$(ifconfig | grep --color=no -Eo 'inet(\s.{2,4}):?([0-9]*\.){3}[0-9]*' | grep --color=no -Eo '([0-9]*\.){3}[0-9]*' | grep --color=no -v '127.0.0.1')
RED='\033[0;31m'
NC='\033[0m' # No Color

if [[ $(which md5) != "" ]]; then
    MD5_CMD=md5
elif [[ $(which md5sum) != "" ]]; then
    MD5_CMD=md5sum
fi

RANDOM_STRING=$(dd if=/dev/urandom bs=1 count=20 2>/dev/null | $MD5_CMD | head -c 10)
rebar3 compile

NODE_NAME="veronica_${RANDOM_STRING}@${IP}"

if [ $? -eq 0 ]; then
    mkdir -p data
    rm -rf data/main
    erl -name ${NODE_NAME} -setcookie veronica -pa _build/default/lib/*/ebin/ -eval -eval 'application:ensure_all_started(veronica).'
else
    printf "${RED}====> Compile error${NC}"
fi
